default: &default
  base_url: "http://localhost:3000"
  client_url: "http://localhost:3001"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  base_url: "http://static.107.116.88.23.clients.your-server.de/"
